# Generated by Django 5.2.11 on 2026-02-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('chart_type', models.CharField(choices=[('bar', 'Bar'), ('line', 'Line'), ('pie', 'Pie')], default='bar', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sales', models.ManyToManyField(related_name='graphs', to='sales.sale')),
            ],
        ),
    ]
